config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  get '/about', to: 'static_pages#about', as: 'about'

  resources :posts



end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to posts_path
    else
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @Post = Post.find(params[:id])

    if @post.update(post_params)
      redirect_to posts_path
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :author, :body)
  end



end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="page-footer">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text">Footer Content</h5>
        <p class="grey-text text-lighten-4">You can use rows and columns here to organize your footer content.</p>
      </div>
      <div class="col l4 offset-l2 s12">
        <h5 class="white-text">Links</h5>
        <ul>
          <li><a class="grey-text text-lighten-3" href="#!">Link 1</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Link 2</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Link 3</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Link 4</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
    © 2014 Copyright Text
    <a class="grey-text text-lighten-4 right" href="#!">More Links</a>
    </div>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<nav>
  <div class="nav-wrapper leffft">
<!--     <p class="brand-logo center orbitron neon" style="color: #47d846;">Welcome to my Online Profile</p> -->
    <ul id="nav-mobile" class="right hide-on-med-and-down orbitron">
      <li><%= link_to 'Home', root_path, :class =>"neon text-glow-hover" %></li>
      <li><%= link_to 'Portfolio', about_path, :class =>"neon" %></li>
      <li><%= link_to 'Resume', posts_path, :class =>"neon" %></li>
      <li><%= link_to 'Posts', posts_path, :class => "neon" %></li>
      <li><%= link_to 'Contact', about_path, :class => "neon" %></li>
      <li><a href="#" data-activates="slide-out" class="right button-collapse"><i class="material-icons">menu</i></a></li>
    </ul>
    <ul>
      <a href="#" data-activates="slide-out" class="right button-collapse"><i class="material-icons">menu</i></a>
    </ul>
  </div>
</nav>

app/views/layouts/_sidenav.html.erb
<ul id="slide-out" class="side-nav fixed">
  <li><div class="userView">
    <%= image_tag("canvas.png", :alt => "Promo Image", :class => "circle profpic responsive-image") %>
    <a href="#!name"><span class="black-text name">Brian</span></a>
    <a href="#!email"><span class="black-text email">phelpsb92@gmail.com</span></a>
  </div></li>
  <li><a href="#!"><i class="material-icons">cloud</i>First Link With</a></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
  <link href="https://fonts.googleapis.com/css?family=Orbitron" rel="stylesheet">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/css/materialize.min.css">
  <title>PersonalProfile</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
</head>
<body>
  <%= render 'layouts/sidenav' %>

  <%= render 'layouts/navbar' %>
<%= yield %>
  <%= render 'layouts/footer' %>
  <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/js/materialize.min.js"></script>
</body>
</html>

app/views/posts/edit.html.erb
<h1> Edit Post </h1>
<%= form_for @post do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :author %>
  <%= f.text_field :author %>

  <%= f.label :body %>
  <%= f.text_field :body %>

  <%= f.submit %>
<% end %>

app/views/posts/index.html.erb
<h1> Posts </h1>
<p><%= link_to 'New Post', new_post_path %></p>
<% @posts.each do |post| %>
  <h3><%= post.title %></h2>
  <h3><%= post.author %></h3>
  <p><%= post.body %></p>
  <%= link_to 'Show post', post_path(post) %>
  <%= link_to 'Edit post', edit_post_path(post) %>
  <%= link_to 'Destroy post', post, method: :delete %>
<% end %>

app/views/posts/new.html.erb
<h1> New Post </h1>
<%= form_for @post do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :author %>
  <%= f.text_field :author %>

  <%= f.label :body %>
  <%= f.text_field :body %>

  <%= f.submit %>
<% end %>

app/views/posts/show.html.erb
<h1> Post </h1>
<h2> <%= @post.title %></h2>
<h3> <%= @post.author %></h3>
<p> <%= @post.body %></p>
<%- link_to 'Back', posts_path %>

app/views/static_pages/about.html.erb
<div class="custom-background">


  <h1 class="white-text">.</h1>
  <h1 class="white-text">.</h1>
  <h1 class="white-text">.</h1>
  <h1 class="white-text">.</h1>
  <h1 class="white-text">.</h1>
  <h1 class="white-text">.</h1>
  <h1 class="white-text">.</h1>
  <h1 class="white-text">.</h1>
  <h1 class="white-text">.</h1>
  <h1 class="white-text">.</h1>
  <h1 class="white-text">.</h1> 



</div>

app/views/static_pages/home.html.erb
<div class="parallax-container">
  <div class="parallax"><%= image_tag("example.gif", :alt => "matrix") %></div>
</div>

  <div class="carousel carousel-slider center" data-indicators="true">
    <div class="carousel-item carouselcolor white-text" href="#one!">
      <div class="row">
        <div class="col m8 offset m2">
          <a target="_blank" href="https://github.com/F1nalFortune/calculator"><%= image_tag('ruby_calc.png', :class => "image") %></a>
        </div>
        <div class="col m2 targetlink">
          <p id="g" class="orbitron neon">g</p>
          <p class="vertword orbitron neon">i</p>
          <p class="vertword orbitron neon">t</p>
          <p class="vertword orbitron neon">H</p>
          <p class="vertword orbitron neon">u</p>
          <p class="vertword orbitron neon">b</p>
          <a href="https://github.com/F1nalFortune/calculator" target="_blank"><span class="fa fa-github fa-2x neon"></span></a>
        </div>
      </div>

    </div>
    <div class="carousel-item carouselcolorone white-text" href="#two!">
      <div class="row">
        <div class="col m8 offset m2">
          <a target="_blank" href="https://github.com/samhammer325/TMix"><%= image_tag('tmix_pic.png', :class => "responsive-image image") %></a>
        </div>
        <div class="col m2 targetlink">
          <p id="g" class="orbitron neon">g</p>
          <p class="vertword orbitron neon">i</p>
          <p class="vertword orbitron neon">t</p>
          <p class="vertword orbitron neon">H</p>
          <p class="vertword orbitron neon">u</p>
          <p class="vertword orbitron neon">b</p>
          <a href="https://github.com/samhammer325/TMix" target="_blank"><span class="fa fa-github fa-2x neon"></span></a>
        </div>
      </div>
    </div>
    <div class="carousel-item carouselcolor white-text" href="#three!">
      <div class="row">
        <div class="col m4 offset-m4">
          <a target="_blank" href="https://github.com/samhammer325/TMix"><%= image_tag('drink_and_thrive.png', :id => "thrive", :class => "responsive-image") %></a>
        </div>
        <div class="col m1 targetlink">
          <p id="g" class="orbitron neon">g</p>
          <p class="vertword orbitron neon">i</p>
          <p class="vertword orbitron neon">t</p>
          <p class="vertword orbitron neon">H</p>
          <p class="vertword orbitron neon">u</p>
          <p class="vertword orbitron neon">b</p>
          <a href="https://github.com/Reyholmgren/drinkandthrive" target="_blank"><span class="fa fa-github fa-2x neon"></span></a>
        </div>
        <div id="hlink" class="col m1">
          <div>
            <p id="g" class="orbitron neon">h</p>
            <p class="vertword orbitron neon">e</p>
            <p class="vertword orbitron neon">r</p>
            <p class="vertword orbitron neon">o</p>
            <p class="vertword orbitron neon">k</p>
            <p class="vertword orbitron neon">u</p>
          </div>
          <a href="drinkandthrive.herokuapp.com" target="_blank"><span class="fa fa-h-square fa-2x neon"></span></a>
        </div>
      </div>
    </div>
    <div class="carousel-item blue white-text" href="#four!">
      <h2>Fourth Panel</h2>
      <p class="white-text">This is your fourth panel</p>
    </div>
  </div>
        

<div class="parallax-container">
  <div class="parallax"><%= image_tag("example.gif", :alt => "matrix") %></div>
</div>

<h1 class="white-text"> Hello WOrld </h1>
<p class="white-text"> Hello WOrld </p>
<%= image_tag("Resume.pdf", :alt => "Promo Image", :class => "circle profpic responsive-image") %>